language: python
python:
  - "3.5"
  - "3.6"
addons:
  postgresql: "9.6"
  apt:
    packages:
      - language-pack-de
services:
  - redis-server
install:
  - "pip install --upgrade pip"
  - "pip install --upgrade pytest"
  - "pip install psycopg2"
before_script:
  - psql -U postgres -c "CREATE DATABASE byceps_test;"
  - psql -U postgres -c "CREATE ROLE byceps_test WITH LOGIN PASSWORD 'test';"
script:
  - "python setup.py test"
dist: trusty
sudo: false
notifications:
  email: false
